<div class="space-y-6">
    <header class="app-page-heading"><h1 class="text-2xl">Form registrasi</h1><p>{{ $activity->title }}</p></header>
    <flux:button :href="route('admin.activity-participants', $activity->id)">Daftar peserta</flux:button>
    @if(session('status'))<p role="status">{{ session('status') }}</p>@endif
    @if($errors->any())<div role="alert" class="rounded-xl bg-red-50 p-4 text-red-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <form wire:submit="save" class="space-y-6">
        <section class="space-y-4 rounded-xl border border-zinc-200 p-6 dark:border-zinc-700"><flux:checkbox wire:model="registrationOpen" label="Tampilkan tombol registrasi dan buka pendaftaran" /><flux:heading>Kategori peserta</flux:heading>@foreach(\App\Services\ActivityEntryService::CATEGORIES as $value=>$label)<flux:checkbox wire:model="categories" :value="$value" :label="$label" />@endforeach<div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="teamMin" type="number" min="1" max="100" label="Minimal anggota Tim/Grup" /><flux:input wire:model="teamMax" type="number" min="1" max="100" label="Maksimal anggota Tim/Grup" /></div><flux:text>Barung: 4–6, Regu: 6–8, Sangga: 4–8 anggota. Setiap pendaftaran wajib satu pembina pendamping dan boleh satu cadangan di luar jumlah anggota utama.</flux:text></section>
        <section class="space-y-4 rounded-xl border border-zinc-200 p-6 dark:border-zinc-700"><flux:heading>Data peserta / Data SIMPRAM</flux:heading><flux:text>Bagian peserta, pembina dan cadangan selalu tersedia. Pilih data SIMPRAM yang berhak diakses atau isi peserta eksternal. Nama, NTA/NIP, sekolah dan kontak tidak dapat dibuat sebagai pertanyaan tambahan.</flux:text></section>
        @foreach($fields as $index=>$field)<section wire:key="field-{{ $field['id'] }}" class="space-y-4 rounded-xl border border-zinc-200 p-6 dark:border-zinc-700"><div class="flex flex-wrap justify-between gap-3"><flux:heading>Pertanyaan {{ $index + 1 }}</flux:heading><div class="flex gap-2"><flux:button size="sm" wire:click="moveField({{ $index }}, -1)">Naik</flux:button><flux:button size="sm" wire:click="moveField({{ $index }}, 1)">Turun</flux:button><flux:button size="sm" wire:click="removeField({{ $index }})">Hapus</flux:button></div></div><flux:input wire:model="fields.{{ $index }}.label" label="Nama field" required maxlength="150" /><flux:textarea wire:model="fields.{{ $index }}.description" label="Deskripsi (opsional)" rows="2" /><flux:select wire:model.live="fields.{{ $index }}.type" label="Jenis jawaban">@foreach(['short_text'=>'Jawaban singkat','paragraph'=>'Paragraf','radio'=>'Pilihan ganda','checkbox'=>'Kotak centang','select'=>'Drop-down','date'=>'Tanggal','time'=>'Waktu','file'=>'Lampiran'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</flux:select>@if(in_array($field['type'], ['radio','checkbox','select']))<flux:textarea wire:model="fields.{{ $index }}.options_text" label="Pilihan (satu per baris)" rows="4" />@endif @if($field['type'] === 'file')<flux:text>Maksimal satu field lampiran: 10 file, masing-masing maksimal 5 MB.</flux:text>@endif<flux:checkbox wire:model="fields.{{ $index }}.required" label="Wajib diisi" /></section>@endforeach
        <flux:button wire:click="addField">Tambah pertanyaan</flux:button>
        <section class="space-y-4 rounded-xl border border-zinc-200 p-6 dark:border-zinc-700"><flux:textarea wire:model="terms" label="Syarat dan ketentuan" rows="6" required /><flux:text>Pernyataan keaslian dan pertanggungjawaban data serta persetujuan ketentuan selalu wajib dicentang sebelum mengirim.</flux:text></section><flux:button type="submit" variant="primary">Simpan formulir</flux:button>
    </form>
</div>
