<?php

return [
    'timezone' => 'Asia/Makassar',
    'pdf_limit' => 1000,
    'actions' => [
        'created' => 'Membuat', 'updated' => 'Mengubah', 'deleted' => 'Menghapus',
        'restored' => 'Memulihkan', 'approved' => 'Menyetujui', 'rejected' => 'Menolak',
        'login' => 'Login', 'logout' => 'Logout', 'downloaded' => 'Mengunduh',
        'exported' => 'Mengekspor', 'imported' => 'Mengimpor', 'uploaded' => 'Mengunggah',
        'sent' => 'Mengirim', 'failed' => 'Gagal', 'password_changed' => 'Mengubah password',
    ],
    'modules' => [
        'students' => 'Siswa', 'attendance' => 'Absensi', 'journals' => 'Jurnal',
        'assessments' => 'Penilaian', 'grades' => 'Nilai', 'letters' => 'Persuratan',
        'archives' => 'Arsip', 'users' => 'Pengguna', 'roles' => 'Hak Akses',
        'schools' => 'Sekolah', 'messaging' => 'Pesan', 'settings' => 'Pengaturan',
        'reports' => 'Laporan',
    ],
    'roles' => [
        'super_admin' => 'Super Admin', 'school_admin' => 'Admin Sekolah',
        'scout_admin' => 'Admin Pramuka', 'coach' => 'Pembina', 'student' => 'Siswa',
        'principal' => 'Kepala Sekolah', 'system' => 'Sistem', 'guest' => 'Tamu',
    ],
    'models' => [
        'Student' => 'students', 'StudentEnrollment' => 'students', 'StudentScoutLevel' => 'students',
        'ScoutUnitMember' => 'students', 'Classroom' => 'students', 'UserTransfer' => 'students',
        'Attendance' => 'attendance', 'AttendanceSession' => 'attendance', 'AttendanceSessionParticipant' => 'attendance',
        'Journal' => 'journals', 'JournalAttachment' => 'journals',
        'AssessmentConfig' => 'assessments', 'AssessmentConfigItem' => 'assessments', 'AssessmentFactor' => 'assessments',
        'ActivityAssessment' => 'assessments', 'ActivityAssessmentCriterion' => 'assessments',
        'ActivityAssessmentScore' => 'grades', 'StudentScore' => 'grades', 'FinalGrade' => 'grades',
        'ActivityAssessmentTarget' => 'grades', 'ActivityAssessmentTargetMember' => 'assessments',
        'GradeScale' => 'grades', 'GradeScaleConfig' => 'grades',
        'Activity' => 'attendance', 'ActivityParticipation' => 'attendance',
        'Letter' => 'letters', 'LetterTemplate' => 'letters', 'LetterType' => 'letters',
        'LetterField' => 'letters', 'LetterDisposition' => 'letters', 'LetterAttachment' => 'letters',
        'ReportVerification' => 'archives', 'SemesterClosure' => 'archives',
        'User' => 'users', 'Coach' => 'users', 'SchoolUserMembership' => 'users',
        'Role' => 'roles', 'Permission' => 'roles',
        'School' => 'schools', 'SchoolRegistrationRequest' => 'schools',
        'MessagingSetting' => 'settings', 'UserNotificationChannel' => 'messaging',
        'Announcement' => 'messaging', 'NotificationLog' => 'messaging',
        'SchoolDocumentSetting' => 'settings', 'SchoolLetterSetting' => 'settings',
        'AttendanceScoreSetting' => 'settings', 'LandingPageSetting' => 'settings',
        'AcademicYear' => 'settings', 'Semester' => 'settings', 'ScoutLevel' => 'settings',
        'ScoutGroup' => 'settings', 'ScoutUnit' => 'settings',
    ],
    'safe_fields' => [
        'id', 'school_id', 'student_id', 'user_id', 'coach_id', 'activity_id', 'journal_id',
        'attendance_session_id', 'academic_year_id', 'semester_id', 'classroom_id', 'scout_level_id',
        'assessment_config_id', 'assessment_factor_id', 'assessment_id', 'criterion_id', 'target_id',
        'grade_scale_config_id', 'letter_id', 'letter_type_id', 'letter_field_id', 'template_id',
        'name', 'school_name', 'npsn', 'level', 'city', 'system_role', 'requested_role',
        'requested_school_id', 'approval_status', 'approved_by', 'reviewed_by', 'status',
        'is_active', 'is_verified', 'enabled', 'channel', 'registration_open', 'timezone',
        'score', 'final_score', 'total_score', 'normalized_score', 'max_score', 'letter_grade', 'grade', 'min_score', 'weight',
        'source', 'source_version', 'attendance_source_version', 'sort_order', 'is_required',
        'is_locked', 'is_special', 'type', 'direction', 'archive_status', 'security_classification',
        'mime_type', 'size_bytes', 'size', 'date', 'attendance_date', 'session_date',
        'start_date', 'end_date', 'joined_at', 'left_at', 'exit_reason', 'published_at',
        'approved_at', 'reviewed_at', 'sent_at', 'deleted_at', 'closed_at',
        'imported', 'failed', 'count', 'format', 'http_status', 'exception_type',
        'role_ids', 'permission_ids', 'student_name', 'from_school_id', 'to_school_id',
    ],
];
