<form method="POST" action="{{ $action }}" enctype="multipart/form-data" class="space-y-5">
    @csrf
    <div class="grid gap-5 sm:grid-cols-2">
        <div><label for="complaint-name" class="mb-2 block text-sm font-semibold">Nama lengkap</label><input id="complaint-name" name="name" value="{{ old('name', $internal ? auth()->user()->name : '') }}" required maxlength="150" @readonly($internal) class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"></div>
        <div><label for="complaint-email" class="mb-2 block text-sm font-semibold">Email</label><input id="complaint-email" type="email" name="email" value="{{ old('email', $internal ? auth()->user()->email : '') }}" required maxlength="150" @readonly($internal) class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"></div>
    </div>
    <div><label for="complaint-category" class="mb-2 block text-sm font-semibold">Kategori pengaduan</label><select id="complaint-category" name="category" required class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"><option value="">Pilih kategori</option>@foreach (\App\Models\Complaint::CATEGORIES as $category)<option @selected(old('category') === $category)>{{ $category }}</option>@endforeach</select></div>
    <div><label for="complaint-subject" class="mb-2 block text-sm font-semibold">Judul pengaduan</label><input id="complaint-subject" name="subject" value="{{ old('subject') }}" required minlength="5" maxlength="180" placeholder="Ringkasan masalah yang ingin disampaikan" class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"></div>
    <div><label for="complaint-body" class="mb-2 block text-sm font-semibold">Uraian kejadian</label><textarea id="complaint-body" name="body" rows="6" required minlength="20" maxlength="10000" placeholder="Jelaskan kejadian, waktu, tempat, dan bantuan yang Anda harapkan." class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100">{{ old('body') }}</textarea></div>
    <div><label for="complaint-attachment" class="mb-2 block text-sm font-semibold">Lampiran bukti <span class="font-normal text-zinc-500">(opsional)</span></label><input id="complaint-attachment" name="attachment" type="file" accept=".jpg,.jpeg,.png,.pdf" aria-describedby="attachment-help" class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"><p id="attachment-help" class="mt-2 text-xs text-zinc-500">JPG, PNG, atau PDF. Maksimal 5 MB. Lampiran hanya dapat diakses pelapor yang login dan pengelola yang berwenang.</p></div>
    <button type="submit" class="inline-flex items-center justify-center rounded-full bg-emerald-800 px-6 py-3 text-sm font-bold text-white hover:bg-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-600">Kirim pengaduan <span aria-hidden="true">&nbsp;→</span></button>
</form>
