<x-layouts::app :title="__('Pengaduan')">
    <div class="space-y-6 p-4 sm:p-6">
        <div class="app-page-heading"><h1 class="text-3xl">{{ $canManage ? 'Kelola pengaduan' : 'Pengaduan saya' }}</h1><p class="mt-3">{{ auth()->user()->isSuperAdmin() ? 'Pengaduan publik dan seluruh sekolah.' : 'Sampaikan kendala dan pantau tindak lanjut dari pengelola sekolah.' }}</p></div>
        @if ($errors->any())<div role="alert" class="rounded-xl bg-red-50 p-5 text-red-800"><ul class="list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @if ($school)
            <details class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900" @if ($errors->any()) open @endif><summary class="cursor-pointer font-bold text-emerald-800 dark:text-emerald-200">Buat pengaduan untuk {{ $school->name }}</summary><div class="mt-6">@include('complaints.form', ['action' => route('complaints.store'), 'internal' => true])</div></details>
        @else
            <p class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900">Pilih sekolah aktif untuk mengirim pengaduan sekolah. Untuk pengaduan umum, gunakan <a href="{{ route('complaints.public') }}" class="font-bold text-emerald-700 underline dark:text-emerald-300">halaman pengaduan publik</a>.</p>
        @endif
        <section class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
            <form method="GET" action="{{ route('complaints.index') }}" class="mb-6 flex flex-col gap-3 sm:flex-row"><div class="flex-1"><label for="complaint-search" class="sr-only">Cari judul atau nomor</label><input id="complaint-search" name="q" value="{{ request('q') }}" placeholder="Cari judul atau nomor pengaduan" class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"></div><div><label for="complaint-status" class="sr-only">Status</label><select id="complaint-status" name="status" class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-3 text-zinc-900 focus:border-emerald-600 focus:outline-emerald-600 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100"><option value="">Semua status</option>@foreach (\App\Models\Complaint::STATUSES as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div><button class="inline-flex items-center justify-center rounded-full bg-emerald-800 px-6 py-3 text-sm font-bold text-white hover:bg-emerald-700 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-600">Tampilkan</button></form>
            <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b border-zinc-200 text-zinc-500 dark:border-zinc-800"><th class="p-3">Pengaduan</th><th class="p-3">Tujuan</th><th class="p-3">Status</th><th class="p-3">Tanggal</th><th class="p-3">Aksi</th></tr></thead><tbody>
                @forelse ($complaints as $complaint)
                    <tr class="border-b border-zinc-100 dark:border-zinc-800"><td class="max-w-sm p-3"><p class="break-words font-semibold">{{ $complaint->subject }}</p><p class="mt-1 break-all text-xs text-zinc-500">{{ $complaint->reference }}</p></td><td class="p-3">{{ $complaint->school?->name ?? 'Publik / Super admin' }}</td><td class="p-3"><span @class(['whitespace-nowrap rounded-full px-3 py-1 text-xs font-bold', 'bg-amber-100 text-amber-900' => $complaint->status === 'new', 'bg-blue-100 text-blue-900' => $complaint->status === 'processing', 'bg-emerald-100 text-emerald-900' => $complaint->status === 'resolved', 'bg-red-100 text-red-900' => $complaint->status === 'rejected'])>{{ \App\Models\Complaint::STATUSES[$complaint->status] }}</span></td><td class="whitespace-nowrap p-3">{{ $complaint->created_at->format('d/m/Y') }}</td><td class="p-3"><a href="{{ route('complaints.show', $complaint->id) }}" data-action-tone="view" class="inline-block rounded-lg px-3 py-2">Detail</a></td></tr>
                @empty<tr><td colspan="5" class="p-10 text-center text-zinc-500">Belum ada pengaduan yang sesuai.</td></tr>@endforelse
            </tbody></table></div><div class="mt-5">{{ $complaints->links() }}</div>
        </section>
    </div>
</x-layouts::app>
