<!DOCTYPE html><html lang="id"><head>@include('partials.head', ['title'=>'Peserta — '.$activity->title])</head>
<body class="simpram-app min-h-screen bg-zinc-50 text-zinc-900 dark:bg-zinc-950 dark:text-zinc-100"><x-public-header /><main class="mx-auto max-w-5xl space-y-6 px-5 py-10">
    <header class="app-page-heading"><h1 class="text-3xl">Peserta kegiatan</h1><p class="mt-2">{{ $activity->title }}</p></header>
    @if(session('status'))<p role="status" class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('status') }}</p>@endif
    <div class="flex flex-wrap gap-3"><flux:button :href="route('public.activities.show', $activity->id)">Detail kegiatan</flux:button>@if($activity->registration_open && in_array($activity->status, ['published','ongoing']) && $activity->end_at?->gt(now()))<flux:button variant="primary" :href="route('public.activities.register', $activity->id)">Daftar peserta</flux:button>@endif</div>
    <p class="text-sm text-zinc-500">Daftar menampilkan peserta aktif yang telah divalidasi pengelola.</p>
    @forelse($entries as $entry)<section class="overflow-hidden rounded-xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><header class="p-5"><h2 class="text-lg font-bold">{{ $entry->name }}</h2><p class="text-sm">{{ \App\Services\ActivityEntryService::CATEGORIES[$entry->category] ?? $entry->category }}</p></header><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-zinc-100 dark:bg-zinc-800"><tr><th class="p-4">Nama</th><th class="p-4">NTA/NIP</th><th class="p-4">Sekolah asal</th><th class="p-4">Peran</th></tr></thead><tbody>@foreach($entry->members as $member)<tr class="border-t border-zinc-100 dark:border-zinc-800"><td class="p-4">{{ $member->name }}</td><td class="p-4">{{ $member->identifier ?: '—' }}</td><td class="p-4">{{ $member->school_name ?: '—' }}</td><td class="p-4">{{ $member->role === 'coach' ? 'Pembina pendamping' : ($member->is_reserve ? 'Cadangan' : 'Peserta') }}</td></tr>@endforeach</tbody></table></div></section>@empty<p class="rounded-xl border border-zinc-200 p-8 text-center dark:border-zinc-700">Belum ada peserta terverifikasi.</p>@endforelse
    {{ $entries->links() }}
</main>@fluxScripts</body></html>
